### ISSUE TITLE
apt-get update: W: Size of file [...] is not what the server reported

### ISSUE THREAD

**Issue by Flint4** [XavierBerger/RPi-Monitor-deb#6] opened 2015-09-20 09:49 UTC
Hi Xavier, 

I get an error while executing apt-get update: 

> W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Packages.gz is not what the server reported 442 152

I use the repo from your project

> deb https://github.com XavierBerger/RPi-Monitor-deb/raw/master/repo/

on my RPi2 (Raspian Jessie). apt-transport-https is installed. 

Any ideas where this issue comes from? Bug in apt-transport-https?

Best wishes, 
Alex

**Comment by mikkelbue** [comment] 2015-09-25 08:25
I second that, running 
Version: 2.10 by Xavier Berger
on 
Linux raspberrypi 4.1.6-v7+ #810 SMP PREEMPT Tue Aug 18 15:32:12 BST 2015 armv7l GNU/Linux

reports:

    W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Release.gpg is not what the server reported 473 152
    W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Release is not what the server reported 1428 148
    W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Packages is not what the server reported 442 152

**Comment by XavierBerger** [comment] 2015-09-26 17:21
I tried to install RPi-Monitor (both devel and master) on my Ubuntu 14.04 and it works fine. I guess the issue is coming from your OS, not from the repository stored on github server.

**Comment by onkelandy** [comment] 2015-10-09 10:17
Same problem here with Linux 4.1.7-v7+ armv7l on Raspi 2.

**Comment by XavierBerger** [comment] 2015-10-09 19:12
It looks that the github repository doesn't work on Raspi2. You should then use directly the .deb to perform installation.

**Comment by Sabcoll** [comment] 2015-10-15 17:43
But this also means that any update and/or upgrade wont work. i get the same error and cant update via apt-get update!

**Comment by floviolleau** [comment] 2015-10-18 18:11
I still have the same problem on a RPI B+. I tried a clean remove / install but with no luck. I have also a RPI2 and have the problem too. Any updates, clues to solve this issue ? I have this message when I run apt-get update.

**Comment by cyberto** [comment] 2015-10-21 13:58
Hi I got the same problem with miniban :(

**Comment by Flint4** [comment] 2015-10-21 17:44
Ok, fortunately it's not just me having troubles. Thats why I filed a bug report in the Debian bug tracker. Lets see what they say about this.

**Comment by franzhartwig** [comment] 2015-11-02 10:55
Same problem here:  RPi2, 4.1.12-v7+, rpimonitor version 2.10-1 installed.
`cat /etc/apt/sources.list.d/rpimonitor.list`
`deb https://github.com XavierBerger/RPi-Monitor-deb/raw/master/repo/`

**Comment by kristofejro** [comment] 2015-11-11 13:52
I have the same problem:

W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Release is not what the server reported 1428 148

W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Packages.gz is not what the server reported 442 152



on my pi:
Debian Linux 8.0
Linux 4.1.12-v7+ on armv7l

**Comment by deMattin** [comment] 2015-11-17 23:48
Confirm the issue on old RPi B with
 RPi-Monitor 2.10
 Raspbian/Debian 7.8
 Linux rpi 4.1.7+ #817:
```
W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Release.gpg is not what the server reported 473 152
W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Release is not what the server reported 1428 148
W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Packages is not what the server reported 442 152
```

**Comment by mcgyver83** [comment] 2015-11-20 11:19
Same for me
'W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Release.gpg is not what the server reported 473 152
W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Release is not what the server reported 1428 148
W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Packages.gz is not what the server reported 442 152
'

Rpi B
Linux 4.1.13+

**Comment by patricktokeeffe** [comment] 2015-12-24 22:19
I see this on a Pi B+ running Raspbian Jessie. However, the [manual install](http://rpi-experiences.blogspot.fr/p/rpi-monitor-installation.html) instructions still work fine.

**Comment by trumad** [comment] 2015-12-28 22:38
I get the same error, but manual installation does not work for me. I get this error when installing the deb:

dpkg-deb: error: `rpimonitor_latest_all.deb' is not a debian format archive

**Comment by RSlegers** [comment] 2015-12-30 21:39
Same problems here with apt-get, on both Rasbian Jessie and Debian Jessie

**Comment by sanchomuzax** [comment] 2016-01-10 19:03
Similar problem...

Processor: ARMv6-compatible processor rev 7 (v6l)
Distribution: Raspbian GNU/Linux 8 (jessie)
Kernel version: Linux 4.1.13+ armv6l
Firmware: #826

**Comment by byjokese** [comment] 2016-01-10 19:23
Same with: 

Processor: ARMv7 Processor rev 5 (v7l)
Distribution: Raspbian GNU/Linux 8 (jessie)
Kernel version: Linux 4.1.15-v7+ armv7l
Firmware: #830

**Comment by andreaskoelsch** [comment] 2016-01-11 15:22
add me to the list.

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

Linux Pi2 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux

**Comment by LennertG** [comment] 2016-01-28 08:04
Same problem..

Processor: ARMv7 Processor rev 5 (v7l)
Distribution: Raspbian GNU/Linux 8 (jessie)
Kernel version: Linux 4.1.13-v7+ armv7l
Firmware: #826

Linux version 4.1.13-v7+

**Comment by zwervers-org** [comment] 2016-01-28 09:06
Same problem here:
Try to update to 2.10 on my RpiB+ Raspbian

**Comment by Flint4** [comment] 2016-02-04 19:07
A quick update: the [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802617) got closed today. It says the issue is expected to be fixed in the newer versions of [apt-transport-https package](https://packages.debian.org/search?keywords=apt-transport-https) (V1.1 and higher). V1.2.1 is currently in testing state so lets hope it gets stable this year.

**Comment by shudack** [comment] 2016-03-15 12:45
Same problem on version 2.10 on my Rpi 3 Raspbian:

W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Release.gpg is not what the server reported 473 152
W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Release is not what the server reported 1428 148
W: Size of file /var/lib/apt/lists/partial/github.com_XavierBerger_RPi-Monitor-deb_raw_master_repo_Packages.gz is not what the server reported 442 152

What i need to do?

**Comment by patricktokeeffe** [comment] 2016-05-18 04:47
Manual instructions appear to not work on the RPi 3 (Raspbian Jessie, Linux 4.4.9-v7):

```
$ sudo dpkg -i rpimonitor_2.10-1_all.deb
dpkg-deb: error: `rpimonitor_2.10-1_all.deb' is not a debian format archive
dpkg: error processing archive rpimonitor_2.10-1_all.deb (--install):
subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
rpimonitor_2.10-1_all.deb
```

**Comment by golfromeo-fr** [comment] 2016-06-21 16:36
@patricktokeeffe 

it seems wget download an XML/HTML file instead of the deb file

the raw download doesn't work anymore this way

**Comment by Kezxo** [comment] 2016-07-01 19:31
This might be a separate issue but every time I do ``apt-get update`` i get this:
```W: Failed to fetch https://github.com/XavierBerger/RPi-Monitor-deb/raw/master/repo/Packages  Bad header line```

**Comment by Gusbenz** [comment] 2016-07-07 13:50
@golfromeo-fr 

Thanks, that worked for me

**Comment by XavierBerger** [comment] 2016-08-17 18:19
Using github as deb repository is not working. I'll update the repository to another site.
To use the new repository, you can update you apt configuration with this file: [/etc/apt/sources.list.d/rpimonitor.list](https://raw.githubusercontent.com/XavierBerger/RPi-Monitor/devel/src/etc/apt/sources.list.d/rpimonitor.list).
**Note**: This repository deliver RPi-Monitor v2.11-beta8
Please let me know is issue is fixed.

**Comment by dusankx** [comment] 2016-08-17 19:26
It seems that the Rpi-Monitor is now updated to version 2.11 after this change. See attached.

![image](https://cloud.githubusercontent.com/assets/7353815/17750115/f3174160-64c0-11e6-8127-847dbc0c8beb.png)

Now, apt-get update throws this error: W: Conflicting distribution: http://giteduberger.fr rpimonitor/ Release (expected rpimonitor but got XavierBerger/RPi-Monitor-deb/raw/{BRANCH}/repo)

Here is the content of my sources.list and sources.list.d/rpimonitor.list files:

```
more /etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian wheezy main firmware
deb http://archive.raspberrypi.org/debian wheezy main
```

```
more /etc/apt/sources.list.d/rpimonitor.list
# RPi-Monitor official repository
# deb https://github.com XavierBerger/RPi-Monitor-deb/raw/master/repo/

deb http://giteduberger.fr rpimonitor/
```

**Comment by XavierBerger** [comment] 2016-08-17 19:51
Thanks for that feedback. It look that github configuration remains in the new repository :-(...
It is fixed now. 
**Note**: I did some tests but as I've rpimonitor already installed + all the "in progress", I may have some side effect. 
Thanks to let me know if now it works better for you.

**Comment by dusankx** [comment] 2016-08-17 20:03
It works! apt-get update runs with no errors:

```
Get:1 http://giteduberger.fr rpimonitor/ Release.gpg [473 B]
Get:2 http://giteduberger.fr rpimonitor/ Release [1394 B]
Get:3 http://giteduberger.fr rpimonitor/ Packages [357 B]
```

Many thanks.

**Comment by XavierBerger** [comment] 2016-08-17 20:12
Cool :-)
Thanks for you quick feedback. This will be the next repository for 2.11 and further.

**Comment by golfromeo-fr** [comment] 2016-08-17 20:39
Thank you @XavierBerger  ;-)

**Comment by deMattin** [comment] 2016-08-17 22:04
Confirmation, that it works now.
Many thanks!

**Comment by trumad** [comment] 2016-08-18 06:53
Fixed - thank you!

**Comment by avma** [comment] 2016-08-18 12:33
Thank you all, it works for: rpi b RASPBIAN JESSIE LITE, rpi 2b and 3b RASPBIAN JESSIE...

**Comment by franzhartwig** [comment] 2016-08-20 15:35
Thank you, it works here, too.
RPi2m Raspbian 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l

**Comment by XavierBerger** [comment] 2016-08-24 17:21
**RPi-Monitor** v2.11 has just been published. Issue is then fixed.

**Closed by XavierBerger** 2016-08-24 17:21 UTC
Labels: bug

**Comment by skylei** [comment] 2017-01-20 07:01
PS C:\docker\mydockerbuild> docker build -t docker-whale .
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM docker/whalesay:latest
 ---> 6b362a9f73eb
Step 2/2 : RUN apt-get -y update
 ---> Running in 4aa31da83cee
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
Hit http://archive.ubuntu.com trusty Release.gpg
Get:3 http://archive.ubuntu.com trusty-updates/main Sources [480 kB]
Get:4 http://archive.ubuntu.com trusty-updates/universe Sources [216 kB]
Get:5 http://archive.ubuntu.com trusty-updates/restricted Sources [480 kB]
Get:6 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1172 kB]
Get:7 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [1172 kB]
Get:8 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [1172 kB]
Hit http://archive.ubuntu.com trusty Release
Get:9 http://archive.ubuntu.com trusty-security/main Sources [1335 kB]
Get:10 http://archive.ubuntu.com trusty-security/restricted Sources [480 kB]
Get:11 http://archive.ubuntu.com trusty-security/universe Sources [1335 kB]
Get:12 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [17.0 kB]
Hit http://archive.ubuntu.com trusty/restricted Sources
Get:13 http://archive.ubuntu.com trusty/universe Sources [216 kB]
Get:14 http://archive.ubuntu.com trusty-security/main amd64 Packages [1172 kB]
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Get:15 http://archive.ubuntu.com trusty/universe amd64 Packages [17.0 kB]
Get:16 http://archive.ubuntu.com trusty-security/universe amd64 Packages [1172 kB]
Hit http://archive.ubuntu.com trusty/main Sources
Fetched 10.6 MB in 50s (208 kB/s)
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_universe_binary-amd64_Packages.gz is not what the server reported 17042 7588885
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/restricted/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/restricted/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/restricted/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/universe/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/restricted/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/universe/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/universe/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/universe/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get -y update' returned a non-zero code: 100
PS C:\docker\mydockerbuild>

**Comment by ajonnet** [comment] 2017-11-13 10:21
Facing similar problem on Raspi3. Unable to install any new package or even doing apt-get update.

Get:1 http://giteduberger.fr rpimonitor/ InRelease
Get:2 http://mirrordirector.raspbian.org jessie InRelease                      
Get:3 http://archive.raspberrypi.org jessie InRelease                          
99% [1 InRelease gpgv 198 B]Splitting up /var/lib/apt/lists/partial/gitedubergerIgn http://giteduberger.fr rpimonitor/ InRelease failed
E: GPG error: http://giteduberger.fr rpimonitor/ InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
